apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume
  namespace: ingress-basic
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: blob-geodata-k8s
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-geodata-k8s
  namespace: ingress-basic
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: blobfusecreds
    options:
      container: geoserverdata
      tmppath: /tmp/blobfuse
      mountoptions: "--file-cache-timeout-in-seconds=120"
